### ISSUE TITLE
Donaciones

### ISSUE THREAD

**Issue by ricciomartin** [PPROF1-2021/g10-a4-g10#15]
Con la idea de monetizar el proyecto, se propone la creación de una pasarela de pago con la idea de que la gente aporte a un banco de árboles, los cuales se adquirirán a un vivero y serán destinados a vecinos sin recursos o entidades sin fines de lucro para fomentar la forestación y/o cuidado del ambiente

**Comment by Estudiantes2021** [comment]
idea modificada
